### ISSUE TITLE
What is the directory "Origine-ACPI" for ?

### ISSUE THREAD

**Issue by MattRvt** [SukkaW/ThinkPad-E480-Hackintosh#1]
https://github.com/SukkaW/ThinkPad-E480-Hackintosh/tree/master/Origin-ACPI

**Comment by SukkaW** [comment]
The DSDT I extracted using Clover F4.

**Comment by MattRvt** [comment]
Okay, it's more or less the same as this for openCore (https://dortania.github.io/Getting-Started-With-ACPI/ssdt-easy.html) 

So just to be sure we have nothing to do with these files?
