### ISSUE TITLE
笔记本电量显示问题

### ISSUE THREAD

**Issue by GrantSJ** [SukkaW/ThinkPad-E480-Hackintosh#10]
sukkaw，你好，非常感谢提供了480的efi，惠及了大众，让广大用户都体验用上了黑果系统。有一个问题，在笔记本接通电源的情况下， 电量显示100%，在拔掉电源时，电量显示只有百分之几十，明显是笔记本没有充电，而是走的电池，接上电源后就开始正常充电。该现象经常发生，我是用同款i5处理器，发现该问题时，是在电脑正常使用时，莫名突然断电了，重启后发现电量为0。后面连续多日验证该问题，时常发生，是确定性问题。版本是10.15.6系统，oc为0.5.8

**Comment by SukkaW** [comment]
ThinkPad E480 的 EC 有问题，所有用这个模具的机器都无解。

**Comment by GrantSJ** [comment]
感谢回复，无解那就只能时常插拔下电源了
