### ISSUE TITLE
E480 使用该OC后不能启动

### ISSUE THREAD

**Issue by ab13sus4** [SukkaW/ThinkPad-E480-Hackintosh#11]
开机启动代码如下
OCB：StartImage failed - Already started
Halting on critical error

**Comment by ab13sus4** [comment]
解决办法：勾选Config-Misc- Boot-HideSelf和Config-Misc- Boot-ShowPicker。安装调试期间，Config-Misc- Boot-Timeout 此项建议20～30秒

**Comment by sobimask** [comment]
U盘开机都进不去 去哪里勾选呢
