### ISSUE TITLE
thinkpad触摸板上的三个按钮怎么设置？

### ISSUE THREAD

**Issue by yipanbo** [SukkaW/ThinkPad-E480-Hackintosh#13]
大佬好，我的机器是thinkpad t470p，想请教下触控板clickpad上的三个按键怎么设置？
现在我用的是https://github.com/acidanthera/VoodooPS2 的驱动，触控手势还算可以，可是触摸板上的三个按钮都是右键的效果，而且点一下右键菜单很快就消失了，所以想请教下怎么把触控板上的三个按钮设置正常，谢谢！

**Comment by SukkaW** [comment]
在 ACPI 中 `KBD` 设备下，添加 `_DSM` Method，定义设备类型为 `LENOVO` 和 `Thinkpad_ClickPad`；注入 `RMCF` 变量，设置 `Thinkoad` 为 `>y` 即可。

**Comment by yipanbo** [comment]
非常感谢！我先试下

**Comment by yipanbo** [comment]
大佬好，你说的前半部分已经改好了，而且触摸板的左键、右键、中间键功能已经正常了。我的T470p不在KBD下，在ps2k下面。
现在触摸板的多指手势不能用了，这个是什么原因呢？是不是RMCF注入有问题？

**Comment by SukkaW** [comment]
> 我的T470p不在KBD下，在ps2k下面

根据 T470P 原始 DSDT，ThinkPad OEM 的 DSDT 中键盘设备名称为 `KBD`： https://github.com/tluck/Lenovo-T460-Clover/blob/master/DSDT.T470p/ACPI-Tables/DSDT.dsl （by @tluck）

因此，请去除 `KBD to PS2K` DSDT 重命名。

**Comment by yipanbo** [comment]
👍
我也是看了tluck的efi文件，把kbd改成ps2k之后，触摸板上的三个按键才起了作用。
我晚上回去去掉重命名试下。
