### ISSUE TITLE
切换双系统导致声卡驱动失效

### ISSUE THREAD

**Issue by Lintao-Zeng** [SukkaW/ThinkPad-E480-Hackintosh#15]
你好，我装了windows和黑苹果双系统，用的是OC引导，但是在每次用完windows后切换到黑苹果系统时，黑苹果系统的声卡驱动就会失效，使用kextload和kextutil命令均无效，只有强制关机或断电才能使驱动恢复，不知道是什么原因造成的，请问有办法解决吗？

**Comment by SukkaW** [comment]
https://github.com/acidanthera/bugtracker/issues/547
