### ISSUE TITLE
OC 0.6.0双硬盘双系统怎么设置引导？

### ISSUE THREAD

**Issue by Lintao-Zeng** [SukkaW/ThinkPad-E480-Hackintosh#16]

**Comment by SukkaW** [comment]
1. 确保 OC 位于装有 macOS 的硬盘的 ESP 分区中
2. 确保 Windows Boot Manager 位于装有 Windows 的硬盘的 ESP 分区中

> 如果由于某种原因（如装有 Windows 的硬盘没有 ESP 分区），你坚持（或不得不）将 Windows Boot Manager 放在装有 macOS 的硬盘的 ESP 分区中，可能需要通过编辑 Windows Boot Manager 的 ESD 文件、使 Windows Boot Manager 能够跨硬盘启动 Windows

3. OC 应该能够自动识别装有 macOS 的硬盘上的 APFS 分区并能正常引导 macOS 启动
4. OC 应该能够自动发现 Windows Boot Manager（不论其在什么硬盘的 ESP 分区中）、并自动调用 Bless Protocol 引导 Windows 启动
5. 在 Windows 下通过 BOOTICE 工具，将 OC 和 Windows Boot Manager 添加到 UEFI 启动项序列中，OC 应该位于最上方、Windows Boot Manager 其次

> 将 Windows Boot Manager 添加到启动项中后，开机时按 F12 可以选择 Windows Boot Manager 启动，用于不通过 OC 引导 Windows 以便于调试。日常使用 Windows 时建议通过 OC 引导以兼容 BootCamp

6. ThinkPad 机型支持锁定启动项，因此重启进入 BIOS，在启动项设置中、锁定启动项不被更改（避免 Windows 更新时覆盖 OC 启动项）

**Comment by Lintao-Zeng** [comment]
根据网上的教程使用OCC配置器打开config.plist，进入Misc取消勾选Hide Self，然后在BlessOverride中添加微软启动项(bootmgfw.efi)。但是我的config.plist中没有Hide Self项，然后我用文本编辑器添加了Hide Self项并设置为false。在启动的时候还是没有出现Windows选项

**Comment by SukkaW** [comment]
> 然后在BlessOverride中添加微软启动项

自 OC 0.5.6 起，OC 支持自动 Bless Windows，无需再将 Windows 启动项添加到 BlessOverrides 中。

如果 OC 无法发现 Windows，请检查 ScanPolicy 相关配置。

**Comment by Lintao-Zeng** [comment]
是的，ScanPolicy设置为0就可以了。可以留个QQ或微信吗？

**Comment by Lintao-Zeng** [comment]
15173951949lll@gmail.com发这个邮箱就行了

**Comment by SukkaW** [comment]
> 可以留个QQ或微信吗？

不通过 QQ 或微信交流。如果愿意，可加入 Telegram 交流群「[黑苹果osx86项目中文讨论](https://t.me/osx86zh)」

**Comment by Lintao-Zeng** [comment]
好的，谢谢

**Comment by Lintao-Zeng** [comment]
还有个问题，在哪设置OC选择启动项的倒计时？
