### ISSUE TITLE
Big sur 11.1

### ISSUE THREAD

**Issue by doellstedter** [SukkaW/ThinkPad-E480-Hackintosh#17]
Cant boot Big sur 11.1 stuck @ Apple Logo without loading bar.

**Comment by SukkaW** [comment]
> Cant boot Big sur 11.1 stuck @ Apple Logo without loading bar.

The EFI hasn't update to OpenCore 0.6.4.

**Comment by doellstedter** [comment]
Okay thx, wich files i have to change. Or will there be an Update from you?

**Comment by SukkaW** [comment]
@doellstedter Hi. The latest commit has OpenCore updated to 0.6.4, with all kexts updated to newest as well. It should be able to boot macOS 11.1 now.
