### ISSUE TITLE
你好，请问是否存在开机必须按fn键调整音量后才有声音的问题吗？

### ISSUE THREAD

**Issue by 543221947** [SukkaW/ThinkPad-E480-Hackintosh#2]
首先感谢分享！我的是翼480，1820A，目前作为主力机的，之前自己弄的效果都不好，后来找到你的替换过来，效果要好的多。

如题，目前主要是开机后必须按fn键调整音量后才有声音，而且你知道的睡眠以后fn不能再按了，以至于如果开机后没有按出声音，则睡眠以后就调不出声音了，请问你的是否存在这个问题，比较纠结，也不知道从哪里排查这个问题。

希望能得到帮助，感谢！

**Comment by SukkaW** [comment]
所以，你能不能按照以下步骤确认一下音量问题：

1. 在 macOS 下关机，然后开机（不要直接重启），是否会有声音？
2. 重启到 Windows 后，直接重启（不是关机开机）到 macOS，是不是会没有声音？
3. 重复 1. 开机是否会有声音？
4. 重启到 Windows 后，关机然后开机，到 macOS 下，开机是否会有声音？

**Comment by 543221947** [comment]
win切换macos这个问题我是知道的，与这个无关
不知道怎么回事，后来专门注意这个问题又不存在了，正常了
后续我再持续关注吗，有问题再讨论，谢谢！
