### ISSUE TITLE
引导windows后睡眠不可用

### ISSUE THREAD

**Issue by ylcz2014** [SukkaW/ThinkPad-E480-Hackintosh#3]
你好，我的电脑也是e480，在另一个硬盘装了黑苹果，用opencore和你的efi，但是在引导windows后
1.盒盖后应该是睡眠，开盖却无法唤醒（键盘鼠标灯亮的）只能强制重启
2.手动睡眠，再按开机键唤醒后键盘无法使用
有什么解决方法吗？
<sub>发自[GeekHub](https://apps.apple.com/cn/app/id1476496206)</sub>

**Comment by SukkaW** [comment]
已知问题，已经确认是由电池补丁导致的 —— L43 函数中调用了唤醒计数器 HWAK 的变量。

我已经修复了，还在自己的机器上测试，之后会更新仓库。

**Comment by ylcz2014** [comment]
测试成功了吗，过了这么长时间怕你忘了。。。。。

**Comment by SukkaW** [comment]
Fixed in https://github.com/SukkaW/ThinkPad-E480-Hackintosh/commit/b92df23a3d9e9c9bde77d368e9ce8942a54cbc34
