### ISSUE TITLE
睡眠唤醒问题

### ISSUE THREAD

**Issue by herofolk** [SukkaW/ThinkPad-E480-Hackintosh#4]
我最近借鉴大佬的efi，发现了同样的问题，深度睡眠唤醒之后Fn没反应了，但是最近opencore升级到了0.5.8，我试了一下，升级到0.5.8的oc没有这个问题了，不知道是我的个例还是别的，期待大佬的测试。

**Comment by 543221947** [comment]
你好，请问你是什么机型？我这边也升级到0.5.8，还是一样不行，奇怪呢，方便加微信交流吗，请问微信号多少？

**Comment by herofolk** [comment]
型号一样E480呀，我发现最近时好时坏的，也没有管它了

**Comment by SukkaW** [comment]
@herofolk @543221947 

S0 睡眠唤醒后 Fn 不受影响，S3 睡眠后受影响。和 OC 无关，和联想的 DSDT、ACPI 有关。

**Comment by GrantSJ** [comment]
sudo pmset -a hibernatemode 0
sudo rm /var/vm/sleepimage
sudo mkdir /var/vm/sleepimage
sudo pmset -a standby 0
sudo pmset -a autopoweroff 0

s0睡眠是这样执行的吗？怎么感觉设置后睡眠唤醒后，fn功能键还是无法使用
