### ISSUE TITLE
请求skk大神帮忙适配x230i

### ISSUE THREAD

**Issue by 13631181823** [SukkaW/ThinkPad-E480-Hackintosh#6]

**Comment by 13631181823** [comment]
敬爱的skk大神您好，本人手中有台x230i，因为才识不足，不知道怎么搞好oc，不知道可不可以协助整一个oc？万分感谢

**Comment by SukkaW** [comment]
@13631181823 如果您能赞助我一台 ThinkPad X230i，我也许可以直接维护一个可用的 EFI；编写黑苹果相关的教程，可以尽力；至于协助，恕难从命。
